# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb_parts}
  s.version = "0.9.14"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Neighman"]
  s.date = %q{2009-11-07}
  s.description = %q{Merb plugin that provides Part Controllers.}
  s.email = %q{has.sox@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "CHANGELOG",
     "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "lib/merb_parts.rb",
     "lib/merb_parts/merbtasks.rb",
     "lib/merb_parts/mixins/parts_mixin.rb",
     "lib/merb_parts/mixins/web_controller.rb",
     "lib/merb_parts/part_controller.rb",
     "lib/merb_parts/version.rb",
     "spec/fixtures/controllers/main.rb",
     "spec/fixtures/parts/done_part.rb",
     "spec/fixtures/parts/todo_part.rb",
     "spec/fixtures/parts/views/layout/todo_part.html.erb",
     "spec/fixtures/parts/views/layout/todo_part.xml.erb",
     "spec/fixtures/parts/views/todo_part/formatted_output.html.erb",
     "spec/fixtures/parts/views/todo_part/formatted_output.js.erb",
     "spec/fixtures/parts/views/todo_part/formatted_output.xml.erb",
     "spec/fixtures/parts/views/todo_part/list.html.erb",
     "spec/fixtures/parts/views/todo_part/part_with_params.html.erb",
     "spec/fixtures/views/main/part_within_view.html.erb",
     "spec/merb-parts_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/merb/merb_parts}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Merb plugin that provides Part Controllers.}
  s.test_files = [
    "spec/fixtures/controllers/main.rb",
     "spec/fixtures/parts/done_part.rb",
     "spec/fixtures/parts/todo_part.rb",
     "spec/merb-parts_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<merb-core>, [">= 0.9.9"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<merb-core>, [">= 0.9.9"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<merb-core>, [">= 0.9.9"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

